= callFlake

`flakelib.lib.callFlake` provides ``callPackage``-like machinery for nix flakes.

== Usage

.flake.nix
[source,nix]
----
{
  inputs = {
    flakelib.url = "github:flakelib/fl";
    nixpkgs = { };
  };
  outputs = { flakelib, ... }@inputs: flakelib {
    inherit inputs;
    config = {
      name = "asdf";
    };
    packages.hey = { lib, writeShellScriptBin, hello }: writeShellScriptBin "hey" ''
      ${hello}/bin/hello -g "${lib.asdf.hey "hi"}"
    '';
    defaultPackage = "hey";
    lib = { lib }: {
      hey = s: s + lib.toUpper s;
    };
  };
}
----

=== Arguments

* `inputs`
* `systems`
* xref:_config[`config`]
* `lib`
* `builders`
* `packages`
* `defaultPackage`
* `checks`
* `apps`
* `defaultApp`
* `devShells`
* `devShell`

=== Config

* `config.name`
* `config.lib.namespace ? [ config.name ]`
* `config.packages.namespace ? []`
* `config.lib.inputs ? attrNames self.inputs`
* xref:_input_config[`config.inputs.${inputName}`]

==== Input Config

* `config`
* `type`: `flake` (default), `src`, `ignore`, `config0`
* `import.${ImportMethod.DefaultImport}`
* `lib.namespace`
* `packages.namespace`
* `aliases`
* `order`

=== Resolver

==== Input Resolution

==== Namespace Flattening

* `inputs`: arguments to `outputs`
* `this`: special reference to attr output
* `lib`: flattened global
* `pkgs`: flattened global
* `callPackage`

==== Context

== Outputs

The following output attrs are generated by `callFlake`:

* `flakes.impure`
* `flakes.outputs` differ from the flake's real `outputs` in the following ways:
** `builders.${system}` is exposed, in contrast to `${flake}.builders` conventionally being a flat set of helpers
** `packages` and related attrs are left unfiltered, exposing incompatible and broken packages
* `flakes.outputs.builders.${system}`

== Outputs Specification

The following output attrs are meaningful when they appear on an input:

* `flakes.config`
* `flakes.import`
